
spring:
  h2:
    console:
      enabled: true
      path: /h2-console


  data:
    web:
      pageable:
        one-indexed-parameters: true # 페이지를 0부터 아니라 1부터 시작하게 해주는 부분
        default-page-size: 5 # 페이지를 몇개 씩 보여주는 설정 하는 부분

  datasource:
    url: jdbc:h2:mem:datePage # test 부분을 자신이 원하는 것으로 바꾸시면 됩니다.
    username: sa # username과 password는 자신의 설정에 맞게
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 어플리케이션을 시작할 때 데이터베이스를 초기화하고 다시 테이블 생성
    properties:
      hibernate:
        format_sql: true # 실행되는 query를 보여줌

logging.level:
  org.hibernate.SQL: debug